//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveDetail
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int NoOfDate { get; set; }
        public string LeaveReason { get; set; }
        public bool Approved { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
